### ISSUE TITLE
When generating images, "laravel-medialibrary" cuts off part of the characters of the file name to the first "-" in the Russian file name

### ISSUE THREAD

**Issue by fomvasss** [spatie/laravel-medialibrary#1287]
I use `"spatie/laravel-medialibrary": "^7.0.0"`
When generating (Save new OR Regenerating) images, "laravel-medialibrary" cuts off part of the characters of the file name to the first "-" in the Russian file name:
```
951
│   ├── conversions
│   │   ├── -min-big.jpg
│   │   ├── -min-list.jpg
│   │   ├── -min-preset.jpg
│   │   ├── -min-preview.jpg
│   │   ├── -min-prev_seen.jpg
│   │   ├── -min-table.jpg
│   │   └── -min-thumb.jpg
│   └── кровать-min.jpg
└── 954
    ├── conversions
    │   ├── life_кровать-шкаф-min-big.jpg
    │   ├── life_кровать-шкаф-min-list.jpg
    │   ├── life_кровать-шкаф-min-preset.jpg
    │   ├── life_кровать-шкаф-min-preview.jpg
    │   ├── life_кровать-шкаф-min-prev_seen.jpg
    │   ├── life_кровать-шкаф-min-table.jpg
    │   └── life_кровать-шкаф-min-thumb.jpg
    └── life_кровать-шкаф-min.jpg
```
https://i.imgur.com/aKQFP4G.jpg

If the file name without the "-" - cuts off completely Russian file name:
```939
│   ├── conversions
│   │   ├── -big.jpg
│   │   ├── -list.jpg
│   │   ├── -preset.jpg
│   │   ├── -preview.jpg
│   │   ├── -prev_seen.jpg
│   │   ├── -table.jpg
│   │   └── -thumb.jpg
│   └── Зеркало.jpg
```
https://i.imgur.com/CPWoZu8.jpg

In ny model (App/Models/Product):
```
public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('preview')
            ->crop('crop-center', 30, 30);

        $this->addMediaConversion('thumb')
            ->crop('crop-center', 50, 50);

        $this->addMediaConversion('prev_seen')
            ->fit('crop', 146, 122);

        $this->addMediaConversion('list')
            ->fit('crop', 528, 528);

        $this->addMediaConversion('table')
            ->fit('crop', 354, 354);

        $this->addMediaConversion('preset')
            ->fit('crop', 146, 146);

        $big = $this->addMediaConversion('big')
            ->fit('fill', 1248, 1248);
    }
```
Php version on server:
```shell
php -v
PHP 7.2.6 (cli) (built: Jun  5 2018 00:52:18) ( NTS )
```

Why is it not possible to apply, for example "str_slug ()" (only without deleting the dot "."), For file names (with extension), while saving them?
For example: "Это мой файл - тест.jpg" -> "eto-moy-fayl-test.jpg"

**Comment by freekmurze** [comment]
I accept a PR that fixes this.

**Comment by Joucke** [comment]
I've tried to reproduce on php 7.2.5, latest version of laravel-medialibrary, cannot reproduce. When adding media to testModelWithConversion, named кровать-min.png, it preserves the conversion's filename properly:
<img width="341" alt="schermafbeelding 2019-01-04 om 10 37 51" src="https://user-images.githubusercontent.com/1655486/50681739-d888b280-100c-11e9-912a-a2b76fa4c07c.png">

**Comment by VincentKos** [comment]
@Joucke same, can't reproduce

**Comment by freekmurze** [comment]
@Joucke @VincentKos thanks for your attempts to reproduce this, highly appreciated 👍 

Going to close this now because it can't be reproduced. If somebody can reproduce this please PR a failing test for me to fix.

**Comment by NormanEdance** [comment]
@freekmurze I confirm it happens. But! file with cyrillic name **uploads to folder correctly** with correct filename, however **url stores in db with cut filename**  so **404 errors occure**. Conversions however partially work with `-thumb.jpg` url.
My quickfix is to use [`usingFileName()`](https://docs.spatie.be/laravel-medialibrary/v7/basic-usage/retrieving-media) with Laravel's helper [`str_slug()`](https://laravel.com/docs/5.7/helpers#method-str-slug)
```
        $contest
                ->addMediaFromRequest('video')
                ->usingFileName('video.'.$request->video->getClientOriginalExtension())
                ->toMediaCollection('contest-videos');
```

**Comment by fomvasss** [comment]
I fixed it in the following way:
Added next string in file `bootstrap/app.php`:
```
setlocale(LC_ALL,'en_US.UTF-8');
```
after code:
```
$app = new Illuminate\Foundation\Application(
    realpath(__DIR__.'/../')
);
```
After it medialibrary working good! :)

But i think it is not perfect way(

**Comment by iraklisg** [comment]
I am also having troubles storing an uploaded file with greek characters in its filename
In particular, when I try to to upload a file with filename `cosmos - κοσμος.pdf`, the `name` field of the `media` table stores the right name (i.e. `cosmos - κοσμος.pdf`) but when I try to upload a file named  `κοσμος - cosmos.pdf` the `name` field of the `media` table gets the wrong value i.e. `- cosmos.pdf` 

Moreover, when I try to upload a file with only greek haracters in its filename, the `name` filed the `media` table gets an empty value

**Comment by igorrebega** [comment]
I also reproduced this bug.
And found exactly why this is happening.

So in "FileAdder" there is the usage of "pathinfo()" function that doesn't work correctly with encoding without set_locale to UTF.

![image](https://user-images.githubusercontent.com/2010915/52519027-c4645080-2c5d-11e9-921b-4cccfd627ed2.png)

But if we add "`setlocale(LC_ALL,'C.UTF-8')`" before `pathinfo()` it will works:

![image](https://user-images.githubusercontent.com/2010915/52519040-11482700-2c5e-11e9-9086-090cf29a0a31.png)

So question is what we should do about it?
1. Make some kind of wrapper to change locale to C.UTF-8 and revert it after.
2. Make programmers set this locale by their own.
3. Try to understand why Laravel don't set this locale by default.

**Comment by iraklisg** [comment]
Do we have an update on this issue? The problem still exists :disappointed: 

@igorrebega may I ask you please what strategy are you using currently to overcome this problem?
Thank you

**Comment by freekmurze** [comment]
Use fix proposed by @fomvasss for now.
